{{- if .Values.apigw.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "devportal.fullname" $ }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.apigw.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ template "apigw.name" . }}
                port: 
                  number: {{ template "apigw.serviceHttpPort" . }}
{{- end }}