{{- if eq .Values.api.db.type "psql" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devportal.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ template "api.dbUser" . }}
  password: {{ template "api.dbPass" . }}
{{ end }}
{{- if and (eq .Values.api.db.type "psql") (not .Values.api.db.external) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "api.db.tlsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devportal.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "devportal.gen-postgres-certs" . | nindent 2 }}
{{- end }}